apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: devorcas-tls
spec:
  secretName: devorcas-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: devorcas.net
  dnsNames:
    - devorcas.net
#  acme:
#    config:
#      - http01:
#          ingressClass: nginx
#        domains:
#          - devorcas.net
